version: "3.9"
services:
  redis:
    image: redis:6
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:14
    restart: always
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
        - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:3000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

volumes:
  redis:
  postgres: