version: "3.9"
services:
  redis:
    image: redis:6
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:14
    restart: always
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
        - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  postgres: